version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/production.Dockerfile
      args:
        RUBY_VERSION: 3.3.0
    volumes:
      - ./backend:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - env.production.env
    environment:
      RAILS_ENV: production
      BUNDLE_PATH: /usr/local/bundle
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      REDIS_URL: ${REDIS_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    command: ./bin/rails server -b 0.0.0.0
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    container_name: "casevault-redis"
    ports:
      - "6379:6379"

  db:
    image: postgres:17
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - env.production.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
  frontend:
    build:
      context: ./frontend
      dockerfile: production.Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  bundle_data:
  pg_data: