version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        RUBY_VERSION: 3.3.0
    volumes:
      - ./backend:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: /usr/local/bundle
      POSTGRES_HOST: db
    command: ./bin/rails server -b 0.0.0.0
    depends_on:
      - db
      - redis
  
  redis:
    image: redis:alpine
    container_name: "casevault-redis"
    ports:
      - "6379:6379"

  db:
    image: postgres:17
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  bundle_data:
  pg_data:
