version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/production.Dockerfile
      args:
        RUBY_VERSION: 3.3.0
    volumes:
      - ./backend:/app
      - bundle_data:/usr/local/bundle
      - storage_data:/app/storage
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    env_file:
      - ./production.env
    environment:
      RAILS_ENV: production
      BUNDLE_PATH: /usr/local/bundle
      POSTGRES_HOST: db
    command: ./bin/rails server -b 0.0.0.0
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    container_name: "casevault-redis"
    ports:
      - "6379:6379"

  db:
    image: postgres:17
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./production.env
    
  frontend:
    build:
      context: ./frontend
      dockerfile: production.Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  bundle_data:
  pg_data:
  storage_data: