name: Deploy App with Rollback

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  COMPOSE_PROJECT_NAME: casevault
  FRONTEND_SERVER: 100.73.82.93

jobs:
  deploy:
    runs-on: [self-hosted, apps-runner]
    env:
      RAILS_ENV: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Create production.env
        run: |
          echo "SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}" >> production.env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> production.env
          echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" >> production.env
          echo "SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> production.env
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> production.env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> production.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> production.env
          echo "HOST_DB_VOLUME_PATH=${{ env.HOST_DB_VOLUME_PATH }}" >> production.env
          echo "POSTGRES_DB=${{ env.POSTGRES_DB }}" >> production.env
          echo "POSTGRES_USER=${{ env.POSTGRES_USER }}" >> production.env


      - name: Create Frontend .env
        run: | 
          echo "VITE_API_CASES_URL=${{ env.VITE_API_CASES_URL }}" >> frontend/.env
          echo "VITE_API_BASE_URL=${{ env.VITE_API_BASE_URL }}" >> frontend/.env
          echo "VITE_API_EXPORT_CASE_URL=${{ env.VITE_API_EXPORT_CASE_URL }}" >> frontend/.env

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan $FRONTEND_SERVER >> ~/.ssh/known_hosts
        
      - name: Deploy static files via rsync over SSH
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
            ./frontend/assets/ deploy@$FRONTEND_SERVER:/var/www/casevault.ethicapp.info

      - name: Tag current image as previous (for rollback)
        run: |
          docker image tag myapp_backend:latest myapp_backend:previous || echo "No existing latest image to tag"
      
      - name: Debug working directory
        run: |
          echo "PWD: $(pwd)"
          ls -al
          echo "Contents of ./deploy:"
          ls -al ./deploy || echo "No ./deploy directory found"

      - name: Build and start new containers
        run: |
          set -e
          docker compose -p $COMPOSE_PROJECT_NAME -f ./docker-compose.production.yml build
          docker compose -p $COMPOSE_PROJECT_NAME -f ./docker-compose.production.yml up -d

      - name: Wait for Rails to boot
        run: sleep 60

      - name: Check running containers
        run: |
          docker ps

      - name: Run Rails migrations
        run: |
          docker compose -p $COMPOSE_PROJECT_NAME -f ./docker-compose.production.yml exec -T casevault-main-backend-1 bundle exec rails db:migrate

      #- name: Smoke test API health
      #  run: |
      #    curl --fail http://localhost:3000/health || (echo "Health check failed" && exit 1)

    # Rollback en caso de fallo
    continue-on-error: false

  rollback:
    needs: deploy
    if: failure()
    runs-on: self-hosted
    steps:
      - name: Rollback to previous image
        run: |
          echo "Rolling back to previous version..."
          docker image tag myapp_backend:previous myapp_backend:latest
          docker compose -p $COMPOSE_PROJECT_NAME -f ./deploy/docker-compose.production.yml up -d
