name: Deploy App with Rollback

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  COMPOSE_PROJECT_NAME: casevault
  FRONTEND_SERVER: 100.73.82.93

jobs:
  deploy:
    runs-on: [self-hosted, apps-runner]
    env:
      RAILS_ENV: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Create production.env
        run: | 
          cat > production.env <<EOF
          SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}
          YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}
          REDIS_URL=${{ secrets.REDIS_URL }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          HOST_DB_VOLUME_PATH=${{ env.HOST_DB_VOLUME_PATH }}
          POSTGRES_DB=${{ env.POSTGRES_DB }}
          POSTGRES_USER=${{ env.POSTGRES_USER }}
          EOF

      - name: Create Frontend .env
        run: | 
          cat > frontend/.env <<EOF
          VITE_API_CASES_URL=${{ env.VITE_API_CASES_URL }}
          VITE_API_BASE_URL=${{ env.VITE_API_BASE_URL }}
          VITE_API_EXPORT_CASE_URL=${{ env.VITE_API_EXPORT_CASE_URL }}
          # other frontend env vars here
          EOF

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan $FRONTEND_SERVER >> ~/.ssh/known_hosts
        
      - name: Deploy static files via rsync over SSH
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
            ./frontend/assets/ deploy@$FRONTEND_SERVER:/var/www/casevault.ethicapp.info

      - name: Tag current image as previous (for rollback)
        run: |
          docker image tag myapp_backend:latest myapp_backend:previous || echo "No existing latest image to tag"

      - name: Build and start new containers
        run: |
          set -e
          docker compose -p $COMPOSE_PROJECT_NAME -f ./deploy/docker-compose.production.yml build
          docker compose -p $COMPOSE_PROJECT_NAME -f ./deploy/docker-compose.production.yml up -d

      - name: Wait for Rails to boot
        run: sleep 60

      - name: Run Rails migrations
        run: |
          docker compose -p $COMPOSE_PROJECT_NAME -f ./deploy/docker-compose.production.yml exec -T web bundle exec rails db:migrate

      #- name: Smoke test API health
      #  run: |
      #    curl --fail http://localhost:3000/health || (echo "Health check failed" && exit 1)

    # Rollback en caso de fallo
    continue-on-error: false

  rollback:
    needs: deploy
    if: failure()
    runs-on: self-hosted
    steps:
      - name: Rollback to previous image
        run: |
          echo "Rolling back to previous version..."
          docker image tag myapp_backend:previous myapp_backend:latest
          docker compose -p $COMPOSE_PROJECT_NAME -f ./deploy/docker-compose.production.yml up -d
